
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN CLASS COMMA CONSTRUCTOR IDENTIFIER LBRACE LPAREN NUMBER PERIOD RBRACE RPAREN SEMICOLON STRING\n    class : CLASS IDENTIFIER LBRACE constructor RBRACE\n    \n    constructor : CONSTRUCTOR LPAREN params RPAREN LBRACE statements RBRACE\n    \n    params : param\n           | param COMMA params\n    \n    param : IDENTIFIER\n    \n    statements : statement\n               | statement statements\n    \n    statement : IDENTIFIER PERIOD IDENTIFIER ASSIGN expression SEMICOLON\n    \n    expression : IDENTIFIER\n               | NUMBER\n               | STRING\n    '
    
_lr_action_items = {'CLASS':([0,],[2,]),'$end':([1,7,],[0,-1,]),'IDENTIFIER':([2,8,13,14,17,21,23,28,],[3,11,11,18,18,22,24,-8,]),'LBRACE':([3,12,],[4,14,]),'CONSTRUCTOR':([4,],[6,]),'RBRACE':([5,16,17,19,20,28,],[7,19,-6,-2,-7,-8,]),'LPAREN':([6,],[8,]),'RPAREN':([9,10,11,15,],[12,-3,-5,-4,]),'COMMA':([10,11,],[13,-5,]),'PERIOD':([18,],[21,]),'ASSIGN':([22,],[23,]),'NUMBER':([23,],[26,]),'STRING':([23,],[27,]),'SEMICOLON':([24,25,26,27,],[-9,28,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'class':([0,],[1,]),'constructor':([4,],[5,]),'params':([8,13,],[9,15,]),'param':([8,13,],[10,10,]),'statements':([14,17,],[16,20,]),'statement':([14,17,],[17,17,]),'expression':([23,],[25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> class","S'",1,None,None,None),
  ('class -> CLASS IDENTIFIER LBRACE constructor RBRACE','class',5,'p_class','yacc_classes.py',6),
  ('constructor -> CONSTRUCTOR LPAREN params RPAREN LBRACE statements RBRACE','constructor',7,'p_constructor','yacc_classes.py',12),
  ('params -> param','params',1,'p_params','yacc_classes.py',18),
  ('params -> param COMMA params','params',3,'p_params','yacc_classes.py',19),
  ('param -> IDENTIFIER','param',1,'p_param','yacc_classes.py',28),
  ('statements -> statement','statements',1,'p_statements','yacc_classes.py',34),
  ('statements -> statement statements','statements',2,'p_statements','yacc_classes.py',35),
  ('statement -> IDENTIFIER PERIOD IDENTIFIER ASSIGN expression SEMICOLON','statement',6,'p_statement','yacc_classes.py',44),
  ('expression -> IDENTIFIER','expression',1,'p_expression','yacc_classes.py',50),
  ('expression -> NUMBER','expression',1,'p_expression','yacc_classes.py',51),
  ('expression -> STRING','expression',1,'p_expression','yacc_classes.py',52),
]
