
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN CLASS COMMA CONSTRUCTOR IDENTIFIER LBRACE LPAREN NUMBER PERIOD RBRACE RPAREN SEMICOLON STRING\n    class : CLASS IDENTIFIER LBRACE constructor RBRACE\n    \n    constructor : CONSTRUCTOR LPAREN params RPAREN LBRACE statements RBRACE\n                | CONSTRUCTOR LPAREN RPAREN LBRACE statements RBRACE\n    \n    params : param\n           | param COMMA params\n    \n    param : IDENTIFIER\n    \n    statements : statement\n               | statement statements\n    \n    statement : IDENTIFIER PERIOD IDENTIFIER ASSIGN expression SEMICOLON\n    \n    expression : IDENTIFIER\n               | NUMBER\n               | STRING\n    '
    
_lr_action_items = {'CLASS':([0,],[2,]),'$end':([1,7,],[0,-1,]),'IDENTIFIER':([2,8,14,15,16,18,24,27,32,],[3,12,19,12,19,19,26,28,-9,]),'LBRACE':([3,10,13,],[4,14,16,]),'CONSTRUCTOR':([4,],[6,]),'RBRACE':([5,17,18,21,22,23,25,32,],[7,22,-7,25,-3,-8,-2,-9,]),'LPAREN':([6,],[8,]),'RPAREN':([8,9,11,12,20,],[10,13,-4,-6,-5,]),'COMMA':([11,12,],[15,-6,]),'PERIOD':([19,],[24,]),'ASSIGN':([26,],[27,]),'NUMBER':([27,],[30,]),'STRING':([27,],[31,]),'SEMICOLON':([28,29,30,31,],[-10,32,-11,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'class':([0,],[1,]),'constructor':([4,],[5,]),'params':([8,15,],[9,20,]),'param':([8,15,],[11,11,]),'statements':([14,16,18,],[17,21,23,]),'statement':([14,16,18,],[18,18,18,]),'expression':([27,],[29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> class","S'",1,None,None,None),
  ('class -> CLASS IDENTIFIER LBRACE constructor RBRACE','class',5,'p_class','yacc_classes.py',6),
  ('constructor -> CONSTRUCTOR LPAREN params RPAREN LBRACE statements RBRACE','constructor',7,'p_constructor','yacc_classes.py',12),
  ('constructor -> CONSTRUCTOR LPAREN RPAREN LBRACE statements RBRACE','constructor',6,'p_constructor','yacc_classes.py',13),
  ('params -> param','params',1,'p_params','yacc_classes.py',22),
  ('params -> param COMMA params','params',3,'p_params','yacc_classes.py',23),
  ('param -> IDENTIFIER','param',1,'p_param','yacc_classes.py',32),
  ('statements -> statement','statements',1,'p_statements','yacc_classes.py',38),
  ('statements -> statement statements','statements',2,'p_statements','yacc_classes.py',39),
  ('statement -> IDENTIFIER PERIOD IDENTIFIER ASSIGN expression SEMICOLON','statement',6,'p_statement','yacc_classes.py',48),
  ('expression -> IDENTIFIER','expression',1,'p_expression','yacc_classes.py',54),
  ('expression -> NUMBER','expression',1,'p_expression','yacc_classes.py',55),
  ('expression -> STRING','expression',1,'p_expression','yacc_classes.py',56),
]
