
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COLON COMMA DQUOTE IDENTIFIER KEYWORD LBRACE NUMBER RBRACE STRINGobject : KEYWORD IDENTIFIER ASSIGN LBRACE instances RBRACEinstances : instance\n             | instance COMMA instances instance :  IDENTIFIER COLON valuevalue : STRING\n             | NUMBER'
    
_lr_action_items = {'KEYWORD':([0,],[2,]),'$end':([1,10,],[0,-1,]),'IDENTIFIER':([2,5,11,],[3,6,6,]),'ASSIGN':([3,],[4,]),'LBRACE':([4,],[5,]),'COLON':([6,],[9,]),'RBRACE':([7,8,12,13,14,15,],[10,-2,-4,-5,-6,-3,]),'COMMA':([8,12,13,14,],[11,-4,-5,-6,]),'STRING':([9,],[13,]),'NUMBER':([9,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'object':([0,],[1,]),'instances':([5,11,],[7,15,]),'instance':([5,11,],[8,8,]),'value':([9,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> object","S'",1,None,None,None),
  ('object -> KEYWORD IDENTIFIER ASSIGN LBRACE instances RBRACE','object',6,'p_object','yacc_object.py',6),
  ('instances -> instance','instances',1,'p_instances','yacc_object.py',10),
  ('instances -> instance COMMA instances','instances',3,'p_instances','yacc_object.py',11),
  ('instance -> IDENTIFIER COLON value','instance',3,'p_instance','yacc_object.py',18),
  ('value -> STRING','value',1,'p_value','yacc_object.py',23),
  ('value -> NUMBER','value',1,'p_value','yacc_object.py',24),
]
