
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN IDENTIFIER KEYWORD NUMBER SEMICOLON STRING\n    variables : KEYWORD IDENTIFIER ASSIGN STRING SEMICOLON \n              | KEYWORD IDENTIFIER ASSIGN NUMBER SEMICOLON\n              | KEYWORD IDENTIFIER SEMICOLON\n    '
    
_lr_action_items = {'KEYWORD':([0,],[2,]),'$end':([1,5,8,9,],[0,-3,-1,-2,]),'IDENTIFIER':([2,],[3,]),'ASSIGN':([3,],[4,]),'SEMICOLON':([3,6,7,],[5,8,9,]),'STRING':([4,],[6,]),'NUMBER':([4,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'variables':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> variables","S'",1,None,None,None),
  ('variables -> KEYWORD IDENTIFIER ASSIGN STRING SEMICOLON','variables',5,'p_variables','yacc_var.py',6),
  ('variables -> KEYWORD IDENTIFIER ASSIGN NUMBER SEMICOLON','variables',5,'p_variables','yacc_var.py',7),
  ('variables -> KEYWORD IDENTIFIER SEMICOLON','variables',3,'p_variables','yacc_var.py',8),
]
